### ISSUE TITLE
It hangs up

### ISSUE THREAD

**Issue by grumagargler** [vahancho/nkar#1] opened 2019-05-16 20:10 UTC
I try to compare two screen shots and see that the app endlessly looping through this recursive procedure:
https://github.com/vahancho/nkar/blob/01dc144849146232fe2771569460dfa621625048/src/comparator.cpp#L263-L279

**Comment by vahancho** [comment] 2019-05-20 07:11
Hi,

Sorry for the late response.
Are you sure the loop is endless? It might be that it processes big images or you run it in the debug mode, which is much more slower.
In order to help you I would need sample screenshots you use or at least a reproducible case. By the way, what are the size of images you compare?

Thanks.

**Comment by vahancho** [comment] 2019-11-06 15:35
There is no answer since May, 2019. I am closing this issue.

**Closed as completed by vahancho** 2019-11-06 15:35 UTC
